version: '3.8'
services:
  database:
    image: mariadb:jammy
    container_name: kairo-tv-db
    ports:
      - 3306:3306
    environment:
      # .env failist loeme sätted
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}" # required
    volumes:
      - ./db/db_container_volume:/var/lib/mysql

  node-api:
    container_name: kairo-tv-API
    build:
      context: ./
      dockerfile: nodeAPI.Dockerfile
    volumes:
      # et automaatne restart toimuks arendamisel
      - ./API:/nodeAPI
      # vastasel juhul ei saa me Dockerfile's installitut kasutada
      - /nodeAPI/node_modules
      # COPY ei funka, sest faili asukoht asub volume sees, mis resetib sisu
      - .env:/nodeAPI/.env
    #command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      DEBUG: nodejs-docker-express:*

  node-front:
    container_name: kairo-tv-node-front
    build:
      context: ./
      dockerfile: nodeFront.Dockerfile
    volumes:
      # et automaatne restart toimuks arendamisel
      - ./kairo-tv-front:/public
      # vastasel juhul ei saa me Dockerfile's installitut kasutada
      - /public/node_modules
    #command: npm run start:dev
    ports:
      - 80:3000
    environment:
      # https://stackoverflow.com/questions/61576659/how-to-hot-reload-in-reactjs-docker
      WATCHPACK_POLLING: "true"

  # front-end:
  #   container_name: kairo-tv-front
  #   build:
  #     context: ./
  #     dockerfile: front.Dockerfile
  #   volumes:
  #    - ./react-front:/usr/share/nginx/html
  #   ports:
  #     - 80:80